/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "checkout": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "dashboard": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}