/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Address not found
 */
export type GetAddressesAddressIdResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Address not found
 */
export class GetAddressesAddressIdResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetAddressesAddressIdResponseBodyData;

  constructor(err: GetAddressesAddressIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "GetAddressesAddressIdResponseBody";
  }
}

/** @internal */
export const GetAddressesAddressIdResponseBody$inboundSchema: z.ZodType<
  GetAddressesAddressIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new GetAddressesAddressIdResponseBody(v);
  });

/** @internal */
export type GetAddressesAddressIdResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const GetAddressesAddressIdResponseBody$outboundSchema: z.ZodType<
  GetAddressesAddressIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetAddressesAddressIdResponseBody
> = z.instanceof(GetAddressesAddressIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAddressesAddressIdResponseBody$ {
  /** @deprecated use `GetAddressesAddressIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAddressesAddressIdResponseBody$inboundSchema;
  /** @deprecated use `GetAddressesAddressIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetAddressesAddressIdResponseBody$outboundSchema;
  /** @deprecated use `GetAddressesAddressIdResponseBody$Outbound` instead. */
  export type Outbound = GetAddressesAddressIdResponseBody$Outbound;
}
