/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Discount not found
 */
export type GetDiscountsDiscountIdResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Discount not found
 */
export class GetDiscountsDiscountIdResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetDiscountsDiscountIdResponseBodyData;

  constructor(err: GetDiscountsDiscountIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "GetDiscountsDiscountIdResponseBody";
  }
}

/** @internal */
export const GetDiscountsDiscountIdResponseBody$inboundSchema: z.ZodType<
  GetDiscountsDiscountIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new GetDiscountsDiscountIdResponseBody(v);
  });

/** @internal */
export type GetDiscountsDiscountIdResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const GetDiscountsDiscountIdResponseBody$outboundSchema: z.ZodType<
  GetDiscountsDiscountIdResponseBody$Outbound,
  z.ZodTypeDef,
  GetDiscountsDiscountIdResponseBody
> = z.instanceof(GetDiscountsDiscountIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDiscountsDiscountIdResponseBody$ {
  /** @deprecated use `GetDiscountsDiscountIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetDiscountsDiscountIdResponseBody$inboundSchema;
  /** @deprecated use `GetDiscountsDiscountIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetDiscountsDiscountIdResponseBody$outboundSchema;
  /** @deprecated use `GetDiscountsDiscountIdResponseBody$Outbound` instead. */
  export type Outbound = GetDiscountsDiscountIdResponseBody$Outbound;
}
