/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Customer not found
 */
export type PatchCustomersCustomerIdResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Customer not found
 */
export class PatchCustomersCustomerIdResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PatchCustomersCustomerIdResponseBodyData;

  constructor(err: PatchCustomersCustomerIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "PatchCustomersCustomerIdResponseBody";
  }
}

/** @internal */
export const PatchCustomersCustomerIdResponseBody$inboundSchema: z.ZodType<
  PatchCustomersCustomerIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new PatchCustomersCustomerIdResponseBody(v);
  });

/** @internal */
export type PatchCustomersCustomerIdResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const PatchCustomersCustomerIdResponseBody$outboundSchema: z.ZodType<
  PatchCustomersCustomerIdResponseBody$Outbound,
  z.ZodTypeDef,
  PatchCustomersCustomerIdResponseBody
> = z.instanceof(PatchCustomersCustomerIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchCustomersCustomerIdResponseBody$ {
  /** @deprecated use `PatchCustomersCustomerIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PatchCustomersCustomerIdResponseBody$inboundSchema;
  /** @deprecated use `PatchCustomersCustomerIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PatchCustomersCustomerIdResponseBody$outboundSchema;
  /** @deprecated use `PatchCustomersCustomerIdResponseBody$Outbound` instead. */
  export type Outbound = PatchCustomersCustomerIdResponseBody$Outbound;
}
