/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Discount not found
 */
export type PatchDiscountsDiscountIdResponseBodyData = {
  message: string;
  error: string;
};

/**
 * Discount not found
 */
export class PatchDiscountsDiscountIdResponseBody extends Error {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: PatchDiscountsDiscountIdResponseBodyData;

  constructor(err: PatchDiscountsDiscountIdResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.error = err.error;

    this.name = "PatchDiscountsDiscountIdResponseBody";
  }
}

/** @internal */
export const PatchDiscountsDiscountIdResponseBody$inboundSchema: z.ZodType<
  PatchDiscountsDiscountIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
})
  .transform((v) => {
    return new PatchDiscountsDiscountIdResponseBody(v);
  });

/** @internal */
export type PatchDiscountsDiscountIdResponseBody$Outbound = {
  message: string;
  error: string;
};

/** @internal */
export const PatchDiscountsDiscountIdResponseBody$outboundSchema: z.ZodType<
  PatchDiscountsDiscountIdResponseBody$Outbound,
  z.ZodTypeDef,
  PatchDiscountsDiscountIdResponseBody
> = z.instanceof(PatchDiscountsDiscountIdResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchDiscountsDiscountIdResponseBody$ {
  /** @deprecated use `PatchDiscountsDiscountIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PatchDiscountsDiscountIdResponseBody$inboundSchema;
  /** @deprecated use `PatchDiscountsDiscountIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PatchDiscountsDiscountIdResponseBody$outboundSchema;
  /** @deprecated use `PatchDiscountsDiscountIdResponseBody$Outbound` instead. */
  export type Outbound = PatchDiscountsDiscountIdResponseBody$Outbound;
}
